language: python
python: 
    - "3.6"
    - "3.7"
    - "3.8"

branches:
    only:
        - master 
        - travis-ci

install:
    #- pip install --upgrade pip 
    - pip install -r requirements.txt
    - ./setup.sh

# TODO : flake8/pylint
# TODO : coverage

# Unit test list 
script:
    - python3 test/test_trainer.py
    - python3 test/test_splitter.py
