language: python
python: 
    - "3.6"
    - "3.7"

branches:
    only:
        - master 
        - travis-ci
install:
  - pip install -U pip
  - pip install --progress-bar off -r requirements.txt
  - ./setup.sh

# TODO : flake8/pylint
# TODO : coverage

# Unit test list 
script:
    - pytest -vv test/
    #- ./test/run_tests.sh
