name: lernomatic
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _pytorch_select=0.1
  - absl-py=0.9.0
  - attrs=19.3.0
  - blas=1.0=mkl
  - c-ares=1.15.0
  - ca-certificates
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cycler=0.10.0
  - freetype=2.9.1
  - grpcio=1.16.1
  - hdf5=1.10.4
  - intel-openmp
  - jpeg=9b
  - kiwisolver=1.2.0
  - gfortran_linux-64
  - libedit=3.1.20181209
  - libffi=3.3
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libtiff=4.1.0
  - markdown=3.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - more-itertools=8.3.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pillow=7.1.2
  - pip=20.0.2
  - pluggy=0.13.1
  - protobuf=3.11.4
  - py=1.8.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pytest=5.4.2
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytorch=1.5.0
  - pytz=2020.1
  - readline=8.0
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.0.0
  - tk=8.6.8
  - torchvision=0.6.0
  - tornado=6.0.4
  - wcwidth=0.1.9
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
